# Generated by Django 5.1.4 on 2026-04-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_time', models.TimeField(default='18:00')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_digest_schedule',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('SAFETY_STOCK_BREACH', 'Safety Stock Breach'), ('SAFETY_STOCK_RECOVERED', 'Safety Stock Recovered'), ('CYCLE_COUNT_VARIANCE', 'Cycle Count Variance'), ('CRAWL_TASK_FAILED', 'Crawl Task Failed'), ('CANARY_ROLLBACK', 'Canary Rollback'), ('SLOW_MOVING_STOCK', 'Slow-Moving Stock'), ('DIGEST', 'Daily Digest'), ('SYSTEM', 'System')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('SAFETY_STOCK_BREACH', 'Safety Stock Breach'), ('SAFETY_STOCK_RECOVERED', 'Safety Stock Recovered'), ('CYCLE_COUNT_VARIANCE', 'Cycle Count Variance'), ('CRAWL_TASK_FAILED', 'Crawl Task Failed'), ('CANARY_ROLLBACK', 'Canary Rollback'), ('SLOW_MOVING_STOCK', 'Slow-Moving Stock'), ('DIGEST', 'Daily Digest'), ('SYSTEM', 'System')], db_index=True, max_length=40)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_subscription',
                'ordering': ['user', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('SMTP', 'Email (SMTP)'), ('SMS', 'SMS Gateway')], max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_outbound_message',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('user', 'event_type')},
        ),
    ]
