# Generated by Django 5.1.4 on 2026-04-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(default='EA', max_length=30)),
                ('costing_method', models.CharField(choices=[('FIFO', 'FIFO'), ('MOVING_AVG', 'Moving Average')], default='MOVING_AVG', max_length=20)),
                ('safety_stock_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ItemLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(db_index=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.item')),
            ],
            options={
                'db_table': 'inventory_item_lot',
                'ordering': ['item', 'received_date'],
                'unique_together': {('item', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='ItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(db_index=True, max_length=150)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('QUARANTINE', 'Quarantine'), ('SCRAPPED', 'Scrapped')], db_index=True, default='AVAILABLE', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.item')),
            ],
            options={
                'db_table': 'inventory_item_serial',
                'ordering': ['item', 'serial_number'],
                'unique_together': {('item', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='warehouse.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_balance',
                'indexes': [models.Index(fields=['item', 'warehouse'], name='inventory_s_item_id_cc960d_idx')],
                'unique_together': {('item', 'warehouse', 'bin')},
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('costing_method', models.CharField(choices=[('FIFO', 'FIFO'), ('MOVING_AVG', 'Moving Average')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('ISSUE', 'Issue'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('CYCLE_COUNT_ADJUST', 'Cycle Count Adjustment')], db_index=True, max_length=30)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.itemlot')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_ledger',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item', 'warehouse', 'timestamp'], name='inventory_s_item_id_e8aa19_idx'), models.Index(fields=['item', 'bin', 'timestamp'], name='inventory_s_item_id_a8df80_idx')],
            },
        ),
    ]
