# Generated by Django 5.1.4 on 2026-04-03 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slow_moving_flagged_at',
            field=models.DateTimeField(blank=True, help_text='Set by Celery task when no issues recorded for 90 days.', null=True),
        ),
        migrations.CreateModel(
            name='CycleCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance_value', models.DecimalField(blank=True, decimal_places=2, help_text='abs(variance_qty) * avg_cost at time of count', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_CONFIRM', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('reason_code', models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Counting Error'), ('DAMAGE', 'Damage / Shrinkage'), ('RECEIVING_ERROR', 'Receiving Error'), ('THEFT', 'Theft / Shortage'), ('OTHER', 'Other')], max_length=30)),
                ('supervisor_note', models.TextField(blank=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions', to='warehouse.bin')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_sessions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions', to='inventory.item')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_session', to='inventory.stockledger')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inventory_cycle_count_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStockBreachState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_started_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField()),
                ('alert_fired', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_states', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_states', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'inventory_safety_stock_breach_state',
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
