# Generated by Django 5.1.4 on 2026-04-03 07:03

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=60)),
                ('crawl_delay_seconds', models.PositiveIntegerField(default=1)),
                ('user_agents', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crawling_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('version_note', models.CharField(blank=True, max_length=500)),
                ('url_pattern', models.CharField(max_length=1000)),
                ('parameters', models.JSONField(default=dict)),
                ('pagination_config', models.JSONField(default=dict)),
                ('request_headers', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_canary', models.BooleanField(db_index=True, default=False)),
                ('canary_pct', models.PositiveSmallIntegerField(default=5)),
                ('canary_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_rule_versions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='crawling.crawlsource')),
            ],
            options={
                'db_table': 'crawling_rule_version',
                'ordering': ['source', '-version_number'],
                'unique_together': {('source', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.SmallIntegerField(db_index=True, default=0)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('checkpoint_page', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawling.crawlruleversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawling.crawlsource')),
            ],
            options={
                'db_table': 'crawling_task',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_url', models.CharField(max_length=2000)),
                ('request_headers', models.TextField(blank=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_snippet', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='crawling.crawltask')),
            ],
            options={
                'db_table': 'crawling_request_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SourceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rpm_limit', models.PositiveIntegerField(default=60)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('held_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='crawling.crawlsource')),
            ],
            options={
                'db_table': 'crawling_source_quota',
            },
        ),
        migrations.AddIndex(
            model_name='crawltask',
            index=models.Index(fields=['status', 'next_retry_at'], name='crawling_ta_status_8b0ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='crawltask',
            index=models.Index(fields=['source', 'status'], name='crawling_ta_source__e41cbc_idx'),
        ),
    ]
