# Generated by Django 5.1.4 on 2026-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting (quota exceeded)'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
